---
name: 01 Basic Docker Build
# simplest workflow possible

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-image:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
            
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Set up Docker Buildx
        id: builder
        uses: docker/setup-buildx-action@v2
        with:
          driver: cloud
          use: true
          install: true
          endpoint: <org>/<builder-amd64>
          platforms: linux/amd64
          append: |
                - endpoint: <org>/<builder-arm64>
                  driver: cloud
                  platforms: linux/arm64
          version: v0.11.2-desktop.1 # Confirm with Kevin

      - name: Docker build
        uses: docker/build-push-action@v5
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: bretfisher/docker-ci-automation:latest,bretfisher/docker-ci-automation:01
